require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DinasController do

  # This should return the minimal set of attributes required to create a valid
  # Dina. As you add validations to Dina, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DinasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all dinas as @dinas" do
      dina = Dina.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dinas).should eq([dina])
    end
  end

  describe "GET show" do
    it "assigns the requested dina as @dina" do
      dina = Dina.create! valid_attributes
      get :show, {:id => dina.to_param}, valid_session
      assigns(:dina).should eq(dina)
    end
  end

  describe "GET new" do
    it "assigns a new dina as @dina" do
      get :new, {}, valid_session
      assigns(:dina).should be_a_new(Dina)
    end
  end

  describe "GET edit" do
    it "assigns the requested dina as @dina" do
      dina = Dina.create! valid_attributes
      get :edit, {:id => dina.to_param}, valid_session
      assigns(:dina).should eq(dina)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Dina" do
        expect {
          post :create, {:dina => valid_attributes}, valid_session
        }.to change(Dina, :count).by(1)
      end

      it "assigns a newly created dina as @dina" do
        post :create, {:dina => valid_attributes}, valid_session
        assigns(:dina).should be_a(Dina)
        assigns(:dina).should be_persisted
      end

      it "redirects to the created dina" do
        post :create, {:dina => valid_attributes}, valid_session
        response.should redirect_to(Dina.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dina as @dina" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dina.any_instance.stub(:save).and_return(false)
        post :create, {:dina => {}}, valid_session
        assigns(:dina).should be_a_new(Dina)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dina.any_instance.stub(:save).and_return(false)
        post :create, {:dina => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dina" do
        dina = Dina.create! valid_attributes
        # Assuming there are no other dinas in the database, this
        # specifies that the Dina created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Dina.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => dina.to_param, :dina => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested dina as @dina" do
        dina = Dina.create! valid_attributes
        put :update, {:id => dina.to_param, :dina => valid_attributes}, valid_session
        assigns(:dina).should eq(dina)
      end

      it "redirects to the dina" do
        dina = Dina.create! valid_attributes
        put :update, {:id => dina.to_param, :dina => valid_attributes}, valid_session
        response.should redirect_to(dina)
      end
    end

    describe "with invalid params" do
      it "assigns the dina as @dina" do
        dina = Dina.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dina.any_instance.stub(:save).and_return(false)
        put :update, {:id => dina.to_param, :dina => {}}, valid_session
        assigns(:dina).should eq(dina)
      end

      it "re-renders the 'edit' template" do
        dina = Dina.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dina.any_instance.stub(:save).and_return(false)
        put :update, {:id => dina.to_param, :dina => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dina" do
      dina = Dina.create! valid_attributes
      expect {
        delete :destroy, {:id => dina.to_param}, valid_session
      }.to change(Dina, :count).by(-1)
    end

    it "redirects to the dinas list" do
      dina = Dina.create! valid_attributes
      delete :destroy, {:id => dina.to_param}, valid_session
      response.should redirect_to(dinas_url)
    end
  end

end
