require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PerfilsZonasController do

  # This should return the minimal set of attributes required to create a valid
  # PerfilsZona. As you add validations to PerfilsZona, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PerfilsZonasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all perfils_zonas as @perfils_zonas" do
      perfils_zona = PerfilsZona.create! valid_attributes
      get :index, {}, valid_session
      assigns(:perfils_zonas).should eq([perfils_zona])
    end
  end

  describe "GET show" do
    it "assigns the requested perfils_zona as @perfils_zona" do
      perfils_zona = PerfilsZona.create! valid_attributes
      get :show, {:id => perfils_zona.to_param}, valid_session
      assigns(:perfils_zona).should eq(perfils_zona)
    end
  end

  describe "GET new" do
    it "assigns a new perfils_zona as @perfils_zona" do
      get :new, {}, valid_session
      assigns(:perfils_zona).should be_a_new(PerfilsZona)
    end
  end

  describe "GET edit" do
    it "assigns the requested perfils_zona as @perfils_zona" do
      perfils_zona = PerfilsZona.create! valid_attributes
      get :edit, {:id => perfils_zona.to_param}, valid_session
      assigns(:perfils_zona).should eq(perfils_zona)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PerfilsZona" do
        expect {
          post :create, {:perfils_zona => valid_attributes}, valid_session
        }.to change(PerfilsZona, :count).by(1)
      end

      it "assigns a newly created perfils_zona as @perfils_zona" do
        post :create, {:perfils_zona => valid_attributes}, valid_session
        assigns(:perfils_zona).should be_a(PerfilsZona)
        assigns(:perfils_zona).should be_persisted
      end

      it "redirects to the created perfils_zona" do
        post :create, {:perfils_zona => valid_attributes}, valid_session
        response.should redirect_to(PerfilsZona.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved perfils_zona as @perfils_zona" do
        # Trigger the behavior that occurs when invalid params are submitted
        PerfilsZona.any_instance.stub(:save).and_return(false)
        post :create, {:perfils_zona => {}}, valid_session
        assigns(:perfils_zona).should be_a_new(PerfilsZona)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PerfilsZona.any_instance.stub(:save).and_return(false)
        post :create, {:perfils_zona => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested perfils_zona" do
        perfils_zona = PerfilsZona.create! valid_attributes
        # Assuming there are no other perfils_zonas in the database, this
        # specifies that the PerfilsZona created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PerfilsZona.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => perfils_zona.to_param, :perfils_zona => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested perfils_zona as @perfils_zona" do
        perfils_zona = PerfilsZona.create! valid_attributes
        put :update, {:id => perfils_zona.to_param, :perfils_zona => valid_attributes}, valid_session
        assigns(:perfils_zona).should eq(perfils_zona)
      end

      it "redirects to the perfils_zona" do
        perfils_zona = PerfilsZona.create! valid_attributes
        put :update, {:id => perfils_zona.to_param, :perfils_zona => valid_attributes}, valid_session
        response.should redirect_to(perfils_zona)
      end
    end

    describe "with invalid params" do
      it "assigns the perfils_zona as @perfils_zona" do
        perfils_zona = PerfilsZona.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PerfilsZona.any_instance.stub(:save).and_return(false)
        put :update, {:id => perfils_zona.to_param, :perfils_zona => {}}, valid_session
        assigns(:perfils_zona).should eq(perfils_zona)
      end

      it "re-renders the 'edit' template" do
        perfils_zona = PerfilsZona.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PerfilsZona.any_instance.stub(:save).and_return(false)
        put :update, {:id => perfils_zona.to_param, :perfils_zona => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested perfils_zona" do
      perfils_zona = PerfilsZona.create! valid_attributes
      expect {
        delete :destroy, {:id => perfils_zona.to_param}, valid_session
      }.to change(PerfilsZona, :count).by(-1)
    end

    it "redirects to the perfils_zonas list" do
      perfils_zona = PerfilsZona.create! valid_attributes
      delete :destroy, {:id => perfils_zona.to_param}, valid_session
      response.should redirect_to(perfils_zonas_url)
    end
  end

end
