require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProbosController do

  # This should return the minimal set of attributes required to create a valid
  # Probo. As you add validations to Probo, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProbosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all probos as @probos" do
      probo = Probo.create! valid_attributes
      get :index, {}, valid_session
      assigns(:probos).should eq([probo])
    end
  end

  describe "GET show" do
    it "assigns the requested probo as @probo" do
      probo = Probo.create! valid_attributes
      get :show, {:id => probo.to_param}, valid_session
      assigns(:probo).should eq(probo)
    end
  end

  describe "GET new" do
    it "assigns a new probo as @probo" do
      get :new, {}, valid_session
      assigns(:probo).should be_a_new(Probo)
    end
  end

  describe "GET edit" do
    it "assigns the requested probo as @probo" do
      probo = Probo.create! valid_attributes
      get :edit, {:id => probo.to_param}, valid_session
      assigns(:probo).should eq(probo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Probo" do
        expect {
          post :create, {:probo => valid_attributes}, valid_session
        }.to change(Probo, :count).by(1)
      end

      it "assigns a newly created probo as @probo" do
        post :create, {:probo => valid_attributes}, valid_session
        assigns(:probo).should be_a(Probo)
        assigns(:probo).should be_persisted
      end

      it "redirects to the created probo" do
        post :create, {:probo => valid_attributes}, valid_session
        response.should redirect_to(Probo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved probo as @probo" do
        # Trigger the behavior that occurs when invalid params are submitted
        Probo.any_instance.stub(:save).and_return(false)
        post :create, {:probo => {}}, valid_session
        assigns(:probo).should be_a_new(Probo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Probo.any_instance.stub(:save).and_return(false)
        post :create, {:probo => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested probo" do
        probo = Probo.create! valid_attributes
        # Assuming there are no other probos in the database, this
        # specifies that the Probo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Probo.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => probo.to_param, :probo => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested probo as @probo" do
        probo = Probo.create! valid_attributes
        put :update, {:id => probo.to_param, :probo => valid_attributes}, valid_session
        assigns(:probo).should eq(probo)
      end

      it "redirects to the probo" do
        probo = Probo.create! valid_attributes
        put :update, {:id => probo.to_param, :probo => valid_attributes}, valid_session
        response.should redirect_to(probo)
      end
    end

    describe "with invalid params" do
      it "assigns the probo as @probo" do
        probo = Probo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Probo.any_instance.stub(:save).and_return(false)
        put :update, {:id => probo.to_param, :probo => {}}, valid_session
        assigns(:probo).should eq(probo)
      end

      it "re-renders the 'edit' template" do
        probo = Probo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Probo.any_instance.stub(:save).and_return(false)
        put :update, {:id => probo.to_param, :probo => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested probo" do
      probo = Probo.create! valid_attributes
      expect {
        delete :destroy, {:id => probo.to_param}, valid_session
      }.to change(Probo, :count).by(-1)
    end

    it "redirects to the probos list" do
      probo = Probo.create! valid_attributes
      delete :destroy, {:id => probo.to_param}, valid_session
      response.should redirect_to(probos_url)
    end
  end

end
