require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RelacionAnimalsController do

  # This should return the minimal set of attributes required to create a valid
  # RelacionAnimal. As you add validations to RelacionAnimal, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RelacionAnimalsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all relacion_animals as @relacion_animals" do
      relacion_animal = RelacionAnimal.create! valid_attributes
      get :index, {}, valid_session
      assigns(:relacion_animals).should eq([relacion_animal])
    end
  end

  describe "GET show" do
    it "assigns the requested relacion_animal as @relacion_animal" do
      relacion_animal = RelacionAnimal.create! valid_attributes
      get :show, {:id => relacion_animal.to_param}, valid_session
      assigns(:relacion_animal).should eq(relacion_animal)
    end
  end

  describe "GET new" do
    it "assigns a new relacion_animal as @relacion_animal" do
      get :new, {}, valid_session
      assigns(:relacion_animal).should be_a_new(RelacionAnimal)
    end
  end

  describe "GET edit" do
    it "assigns the requested relacion_animal as @relacion_animal" do
      relacion_animal = RelacionAnimal.create! valid_attributes
      get :edit, {:id => relacion_animal.to_param}, valid_session
      assigns(:relacion_animal).should eq(relacion_animal)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RelacionAnimal" do
        expect {
          post :create, {:relacion_animal => valid_attributes}, valid_session
        }.to change(RelacionAnimal, :count).by(1)
      end

      it "assigns a newly created relacion_animal as @relacion_animal" do
        post :create, {:relacion_animal => valid_attributes}, valid_session
        assigns(:relacion_animal).should be_a(RelacionAnimal)
        assigns(:relacion_animal).should be_persisted
      end

      it "redirects to the created relacion_animal" do
        post :create, {:relacion_animal => valid_attributes}, valid_session
        response.should redirect_to(RelacionAnimal.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved relacion_animal as @relacion_animal" do
        # Trigger the behavior that occurs when invalid params are submitted
        RelacionAnimal.any_instance.stub(:save).and_return(false)
        post :create, {:relacion_animal => {}}, valid_session
        assigns(:relacion_animal).should be_a_new(RelacionAnimal)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RelacionAnimal.any_instance.stub(:save).and_return(false)
        post :create, {:relacion_animal => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested relacion_animal" do
        relacion_animal = RelacionAnimal.create! valid_attributes
        # Assuming there are no other relacion_animals in the database, this
        # specifies that the RelacionAnimal created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RelacionAnimal.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => relacion_animal.to_param, :relacion_animal => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested relacion_animal as @relacion_animal" do
        relacion_animal = RelacionAnimal.create! valid_attributes
        put :update, {:id => relacion_animal.to_param, :relacion_animal => valid_attributes}, valid_session
        assigns(:relacion_animal).should eq(relacion_animal)
      end

      it "redirects to the relacion_animal" do
        relacion_animal = RelacionAnimal.create! valid_attributes
        put :update, {:id => relacion_animal.to_param, :relacion_animal => valid_attributes}, valid_session
        response.should redirect_to(relacion_animal)
      end
    end

    describe "with invalid params" do
      it "assigns the relacion_animal as @relacion_animal" do
        relacion_animal = RelacionAnimal.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RelacionAnimal.any_instance.stub(:save).and_return(false)
        put :update, {:id => relacion_animal.to_param, :relacion_animal => {}}, valid_session
        assigns(:relacion_animal).should eq(relacion_animal)
      end

      it "re-renders the 'edit' template" do
        relacion_animal = RelacionAnimal.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RelacionAnimal.any_instance.stub(:save).and_return(false)
        put :update, {:id => relacion_animal.to_param, :relacion_animal => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested relacion_animal" do
      relacion_animal = RelacionAnimal.create! valid_attributes
      expect {
        delete :destroy, {:id => relacion_animal.to_param}, valid_session
      }.to change(RelacionAnimal, :count).by(-1)
    end

    it "redirects to the relacion_animals list" do
      relacion_animal = RelacionAnimal.create! valid_attributes
      delete :destroy, {:id => relacion_animal.to_param}, valid_session
      response.should redirect_to(relacion_animals_url)
    end
  end

end
