require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ZonasController do

  # This should return the minimal set of attributes required to create a valid
  # Zona. As you add validations to Zona, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ZonasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all zonas as @zonas" do
      zona = Zona.create! valid_attributes
      get :index, {}, valid_session
      assigns(:zonas).should eq([zona])
    end
  end

  describe "GET show" do
    it "assigns the requested zona as @zona" do
      zona = Zona.create! valid_attributes
      get :show, {:id => zona.to_param}, valid_session
      assigns(:zona).should eq(zona)
    end
  end

  describe "GET new" do
    it "assigns a new zona as @zona" do
      get :new, {}, valid_session
      assigns(:zona).should be_a_new(Zona)
    end
  end

  describe "GET edit" do
    it "assigns the requested zona as @zona" do
      zona = Zona.create! valid_attributes
      get :edit, {:id => zona.to_param}, valid_session
      assigns(:zona).should eq(zona)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Zona" do
        expect {
          post :create, {:zona => valid_attributes}, valid_session
        }.to change(Zona, :count).by(1)
      end

      it "assigns a newly created zona as @zona" do
        post :create, {:zona => valid_attributes}, valid_session
        assigns(:zona).should be_a(Zona)
        assigns(:zona).should be_persisted
      end

      it "redirects to the created zona" do
        post :create, {:zona => valid_attributes}, valid_session
        response.should redirect_to(Zona.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved zona as @zona" do
        # Trigger the behavior that occurs when invalid params are submitted
        Zona.any_instance.stub(:save).and_return(false)
        post :create, {:zona => {}}, valid_session
        assigns(:zona).should be_a_new(Zona)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Zona.any_instance.stub(:save).and_return(false)
        post :create, {:zona => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested zona" do
        zona = Zona.create! valid_attributes
        # Assuming there are no other zonas in the database, this
        # specifies that the Zona created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Zona.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => zona.to_param, :zona => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested zona as @zona" do
        zona = Zona.create! valid_attributes
        put :update, {:id => zona.to_param, :zona => valid_attributes}, valid_session
        assigns(:zona).should eq(zona)
      end

      it "redirects to the zona" do
        zona = Zona.create! valid_attributes
        put :update, {:id => zona.to_param, :zona => valid_attributes}, valid_session
        response.should redirect_to(zona)
      end
    end

    describe "with invalid params" do
      it "assigns the zona as @zona" do
        zona = Zona.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Zona.any_instance.stub(:save).and_return(false)
        put :update, {:id => zona.to_param, :zona => {}}, valid_session
        assigns(:zona).should eq(zona)
      end

      it "re-renders the 'edit' template" do
        zona = Zona.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Zona.any_instance.stub(:save).and_return(false)
        put :update, {:id => zona.to_param, :zona => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested zona" do
      zona = Zona.create! valid_attributes
      expect {
        delete :destroy, {:id => zona.to_param}, valid_session
      }.to change(Zona, :count).by(-1)
    end

    it "redirects to the zonas list" do
      zona = Zona.create! valid_attributes
      delete :destroy, {:id => zona.to_param}, valid_session
      response.should redirect_to(zonas_url)
    end
  end

end
